use custom_deps instead of the DEPS file
But there are issues like this:
    $ gclient sync -D
    Syncing projects: 100% (104/104), done.

    ________ running 'python3 engine/src/flutter/third_party/dart/tools/generate_package_config.py' in '/data/android13/flutter/sources/flutter-upstream/flutter-liuyq'
    `pub get` failed
    Because _ depends on pub_formats from path which doesn't exist (could not find package pub_formats at "third_party/pkg/native/pkgs/pub_formats"), version solving failed.

    Resolving dependencies...

    Error: Command 'python3 engine/src/flutter/third_party/dart/tools/generate_package_config.py' returned non-zero exit status 255 in /data/android13/flutter/sources/flutter-upstream/flutter-liuyq
    `pub get` failed
    Because _ depends on pub_formats from path which doesn't exist (could not find package pub_formats at "third_party/pkg/native/pkgs/pub_formats"), version solving failed.

    Resolving dependencies...

    Warnings:
    git update is recommended.
    Installed git version is 2.25.1;
    depot_tools recommends version 2.46.0 or later.
    Disable this warning by setting the GCLIENT_SUPPRESS_GIT_VERSION_WARNING
    environment variable to 1.
    09:04:47 P15v:flutter-liuyq$ ./bin/flutter pub get
    Downloading Linux x64 Dart SDK from Flutter engine b15356702b41d3bd6a857d588ab21e85e54c174a...
    dart-sdk-url: https://flutter-ohos.obs.cn-south-1.myhuaweicloud.com/flutter_infra_release/flutter/b15356702b41d3bd6a857d588ab21e85e54c174a/dart-sdk-linux-x64.zip
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  197M  100  197M    0     0  10.1M      0  0:00:19  0:00:19 --:--:-- 12.4M
    Building flutter tool...
    Resolving dependencies... (3.0s)
    Downloading packages...
    Got dependencies.
    Error: Couldn't resolve the package 'json5' in 'package:json5/json5.dart'.
    packages/flutter_tools/lib/src/project.dart:8:8: Error: Not found: 'package:json5/json5.dart'
    import 'package:json5/json5.dart';

the engine version of b15356702b41d3bd6a857d588ab21e85e54c174a is defined
in file bin/internal/engine.ohos.version, and used by bin/internal/update_engine_version.sh,
but not sure how it is used by flutter pub get command
and how the engine is used here

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>