engine: hooks: 'argparse' has no attribute error
which is reported when run gclient sync on Ubunutu20.04
with Python 3.8.10:
    Traceback (most recent call last):
      File "engine/src/flutter/tools/githooks/setup.py", line 61, in <module>
        sys.exit(Main(sys.argv))
      File "engine/src/flutter/tools/githooks/setup.py", line 29, in Main
        parser.add_argument('--unset', action=argparse.BooleanOptionalAction, default=False)
    AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>